import "./globals.css";

import Main from "./common/main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Main children={children} />
      </body>
    </html>
  );
}
