import "./globals.css";

import Main from "./layouts/main/main";
import CommonLayout from "./layouts/common/commonlayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <CommonLayout children={children} />
      </body>
    </html>
  );
}
